list-me/listme-front

src/components/CustomTable/index.tsx
src/components/Dragger/index.tsx
src/components/DropdownMenu/index.tsx
src/components/Dropzone/Dropzone.d.ts
src/components/Dropzone/index.tsx
src/components/Dropzone/styles.ts
src/components/RepDropdownMenu/index.tsx
src/components/TableField/TableField.d.ts
src/components/TableField/index.tsx
src/context/images/image.context.d.ts
src/context/images/index.tsx
src/context/products/index.tsx
src/pages/products/styles.ts
src/services/apis/requests/file.ts

Context: Users can drop files of any type into the designated cell.

Feat: cell files to dropzone

---

src/assets/drop-down.svg
src/assets/icons/editors/chevron-down.svg
src/components/CustomTable/index.tsx
src/components/Profile/index.tsx
src/pages/products/styles.ts

- Change chevron icon
- Custom button on multi options template columns

Feature: Add buttons on multi options template columns

---

src/components/CustomTable/components/DefaultTable/utils/customRendererFile.ts
src/components/CustomTable/components/DefaultTable/utils/handleAfterScrollVertically.ts

Adiçao de variavel de controle de fetching

feat: adiçao de uma variavel de fetch em andamento

---

src/components/CustomTable/components/DefaultTable/utils/handleAfterScrollVertically.ts
src/components/CustomTable/components/HeaderFilters/index.tsx
src/components/CustomTable/index.tsx
src/components/RepDropdownMenu/index.tsx
src/context/products/index.tsx
src/context/products/product.context.d.ts
src/pages/products/index.tsx

Ajustes de tipagem relacionado ao get de produtos

feat: tipagens de get products

---

src/components/CustomTable/CustomTable.d.ts
src/components/CustomTable/components/DefaultTable/DefaultTable.d.ts
src/components/CustomTable/components/DefaultTable/index.tsx
src/components/CustomTable/components/DefaultTable/utils/customRendererFile.ts
src/components/CustomTable/components/DefaultTable/utils/getStyledContent.tsx
src/components/CustomTable/components/DefaultTable/utils/handleAfterScrollVertically.ts
src/components/CustomTable/components/HeaderDropDown/HeaderDropDown.d.ts
src/components/CustomTable/components/HeaderDropDown/components/Cell/Cell.d.ts
src/components/CustomTable/components/HeaderDropDown/components/Cell/index.tsx
src/components/CustomTable/components/HeaderDropDown/components/Cell/styles.ts
src/components/CustomTable/components/HeaderDropDown/components/NewColumn/RelationForm/RelationForm.d.ts
src/components/CustomTable/components/HeaderDropDown/components/NewColumn/RelationForm/index.tsx
src/components/CustomTable/components/HeaderDropDown/components/NewColumn/RelationForm/styles.ts
src/components/CustomTable/components/HeaderDropDown/components/NewColumn/index.tsx
src/components/CustomTable/components/HeaderDropDown/components/NewColumn/styles.ts
src/components/CustomTable/components/HeaderDropDown/index.tsx
src/components/CustomTable/components/HeaderDropDown/styles.ts
src/components/CustomTable/index.tsx
src/components/DropdownMenu/index.tsx
src/context/products/index.tsx
src/context/products/product.context.d.ts

Feat otimizacao

---

src/components/CustomTable/components/DefaultTable/index.tsx
src/components/CustomTable/components/DefaultTable/utils/customRendererFile.ts
src/components/CustomTable/index.tsx
src/components/CustomTable/styles.ts

resolvendo problemas na tabela

fix: conflitos

---

src/context/products/index.tsx
src/services/apis/requests/product.ts
src/services/apis/requests/template.ts

fix: adjusts for route and response

---

src/components/CustomTable/index.tsx

fix: undefined alterando o rerender com o colheaders

---

src/components/CustomTable/components/DefaultTable/index.tsx
src/components/CustomTable/components/DefaultTable/utils/handleAfterColumnMove.ts
src/components/CustomTable/index.tsx
src/components/EditableText/index.tsx
src/context/products/index.tsx

Bugs 290923

---

src/components/CustomTable/components/DefaultTable/utils/handleAfterColumnMove.ts
src/context/products/index.tsx

Resolve: Ao dar o freeze em duas colunas e mover a terceira coluna para o lugar da segunda de primeira ele substitui a segunda coluna pela nova que foi movida (o correto), mas após atualizar a página ela volta a estar em segundo e a nova coluna movida aparece tbm como fixada

Fix 021023

---

src/components/Sidebar/index.tsx
src/components/Sidebar/styles.ts
src/components/Table/index.tsx
src/components/TemplateDefault/index.tsx
src/pages/templates/index.tsx
src/routes/index.tsx
src/styles/globalStyles.ts

Fix do Layout de template: Alteraçoes importantes no Sidebar e na listagem do custom table

fix -layout do template: listagem e sidebar

---

src/components/Header/index.tsx
src/components/TemplateDefault/index.tsx
src/pages/templates/index.tsx
src/pages/templates/templates.d.ts
src/services/apis/requests/template.ts

feat: create new template

---

src/components/CustomTable/components/DefaultTable/index.tsx
src/context/products/index.tsx

fix: mover colunas

---

src/components/Filter/components/ConditionFilterComponent/index.tsx
src/components/Filter/components/MultiSelect/index.tsx
src/components/Filter/components/SingleSelect/index.tsx
src/components/Filter/index.tsx

- clique no select pra fechar
- buscar aod eletar palavra
- limpar filtros

Fix filter vm

---

src/components/CustomTable/index.tsx
src/context/products/index.tsx

Corrige o erro de deletar imagens da tabela

fix delete image

---

src/components/CustomModa/index.tsx
src/components/CustomTable/components/DefaultTable/index.tsx
src/components/CustomTable/components/DefaultTable/utils/customRendererFile.ts
src/components/CustomTable/index.tsx
src/context/products/index.tsx

Lm 421 - correçoes

---

src/components/CustomTable/components/HeaderFilters/index.tsx
src/components/Input/Input.d.ts
src/components/Input/index.tsx
src/components/Integration/FeatureForms/index.tsx
src/components/Integration/IntegrationForms/CharacteriscFormIntegration/index.tsx
src/components/Integration/IntegrationForms/DefaultFormIntegration/index.tsx
src/components/Integration/IntegrationNavigate/index.tsx
src/components/Integration/IntegrationNavigate/styles.ts
src/components/Temp/index.tsx
src/context/IntegrationContext/index.tsx
src/services/apis/requests/integration.ts

- Task de erros
- Desabilitar botao limpar ao concluir
- Filtrar Listagem de Templates
- Fix nos formularios adicionais de caracteristicas

Feat integration main

---

src/components/Integration/IntegrationForms/CharacteriscFormIntegration/index.tsx
src/pages/integration/index.tsx
src/services/apis/requests/integration.ts

- fix coluna de relacionamento
- deletar integraçao

fix: relation - feat: delete integration

---

src/components/Dropzone/index.tsx
src/components/Integration/Error/ButtonError/index.tsx
src/components/Integration/Error/SidebarError/components/PaginationSidebarError/index.tsx
src/components/Integration/Error/SidebarError/components/PaginationSidebarError/styles.ts
src/components/Integration/Error/SidebarError/index.tsx

- fix em Paginação de erros
- fix em rota de delete

Feat integ

---

src/components/CustomTable/components/DefaultTable/utils/customRendererFile.ts
src/components/Filter/components/ConditionFilterComponent/index.tsx
src/pages/products/styles.ts

- Tracejado ao arrastar arquivo encima da celular
- Ajuste no filtro para nao quebrar quando demorar a carregar as marcas

fix: dragover dashed

---

src/components/CustomTable/components/DefaultTable/utils/handleAfterPaste.ts
src/context/products/index.tsx

Fix: Cópia e Cola
